### ISSUE TITLE
Review #1 del desafío

### ISSUE THREAD

**Issue by tobiasfacello** [RAS111/dwf-m5-desafio#1]
Hola Rodrigo, felicidades por haber finalizado el desafío del módulo!
Poco tengo para recalcar, el funcionamiento de la webapp es el adecuado, a lo sumo unos detalles visuales a tener en cuenta (claramente, nada que influya en el funcionamiento como tal de la webapp). Así que de mi parte **LGTM**.
Éxitos con el módulo que sigue! 🚀

**Comment by RAS111** [comment]
muchísimas gracias!
